# Generated by Django 5.2.6 on 2025-09-30 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('email', models.CharField(max_length=80)),
                ('phone', models.IntegerField()),
                ('desc', models.CharField(max_length=100)),
            ],
        ),
    ]
